version: "1.0.3"
slug: "sms-gateway"
name: "SMS Gateway"
description: "SMS Gateway using Huawei modem (12d1:1506)"
url: "https://github.com/nnar1o/ha/tree/main/sms-gateway"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
uart: true
usb: true
auth_api: true
homeassistant_api: true
map:
  - share:rw
options:
  device: "/dev/ttyUSB0"
  debug: false
  notification_on_receive: true
  mqtt:
    broker: "core-mosquitto"
    port: 1883
    username: ""
    password: ""
schema:
  device: str
  debug: bool
  notification_on_receive: bool
  mqtt:
    broker: str
    port: port
    username: str?
    password: str?
