name: "SMS Gateway"
version: "1.0.0"
slug: "sms-gateway"
description: "SMS Gateway using Huawei modem (12d1:1506)"
url: "https://github.com/nnar1o/ha/tree/main/sms-gateway"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
usb: true
devices:
  - /dev/ttyUSB0
auth_api: true
homeassistant_api: true
options:
  device: "/dev/ttyUSB0"
  debug: false
  notification_on_receive: true
  mqtt:
    broker: "core-mosquitto"
    port: 1883
    username: ""
    password: ""
schema:
  device: "str"
  debug: "bool"
  notification_on_receive: "bool"
  mqtt:
    broker: "str"
    port: "port"
    username: "str?"
    password: "str?"
